site_name: NIHAO-LIUZHAOYANG
site_author: ZhaoyangLiu
site_description: NIHAO-LIUZHAOYANG
repo_url: https://github.com/LIUZHAOYANG666/NIHAO-LIUZHAOYANG
edit_uri: edit/main/docs/

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      use_pygments: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: True
  - pymdownx.superfences

nav:
  - 主页: "index.md" 
    - 2024年12月21日: "2024年12月21日.md"


plugins:
    - glightbox
    - search
    # - git-revision-date-localized:
    #     enable_creation_date: true
    - link-marker
    - minify:
        minify_html: true
        minify_js: true
        minify_css: true
        htmlmin_opts:
          remove_comments: true
        cache_safe: true

theme:
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - search.suggest
    - search.share
    - toc.integrate
  icon:
    annotation: material/arrow-right-circle
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式